version: "3.0"

services:
  hacknu-db:
    container_name: "hacknu-db"
    image: postgres:14.1-alpine
    env_file:
      - .env
    ports:
      - "9006:5432"
    restart: always
    networks:
      - hacknu-local-version
  
  hacknu-api:
    build: backend/
    env_file: .env
    ports:
      - "8080:8080"
    restart: always
    networks:
      - hacknu-local-version

networks:
  hacknu-local-version:
    external: true

